### ISSUE TITLE
FFFGen - Incorrect orientation, incorrect scale error

### ISSUE THREAD

**Issue by amitjc** [lsimic/FFFGenBlender#1]
Dear Sir,

At the outset, Thank you for the awesome plugin and video documentation.

I tried to follow along the tutorial however, encountered "Possible Incorrect orientation, Possible incorrect scale" error.

Please find the error details below:

```
bpy.context.scene.FFFGenPropertyGroup.fibula_object = None
bpy.context.scene.FFFGenPropertyGroup.mandible_object = None
bpy.context.scene.FFFGenPropertyGroup.auto_decimate = True
bpy.context.scene.FFFGenPropertyGroup.segment_count = 2
bpy.ops.object.modifier_apply(modifier="decimate")
bpy.ops.object.modifier_apply(modifier="decimate")
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.armature_add(enter_editmode=False, align='WORLD', location=(0, 0, 0), scale=(1, 1, 1))
bpy.ops.object.editmode_toggle()
bpy.ops.armature.select_all(action='SELECT')
bpy.ops.armature.delete()
bpy.ops.armature.bone_primitive_add(name="bone.0")
bpy.ops.armature.select_all(action='DESELECT')
bpy.ops.armature.bone_primitive_add(name="bone.1")
bpy.ops.armature.select_all(action='DESELECT')
bpy.ops.armature.bone_primitive_add(name="bone.2")
bpy.ops.armature.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.parent_set(type='ARMATURE')
bpy.ops.object.parent_set(type='ARMATURE')
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.empty_add(type='ARROWS', align='WORLD', location=(0, 0, 0), scale=(1, 1, 1))
bpy.ops.object.empty_add(type='ARROWS', align='WORLD', location=(0, 0, 0), scale=(1, 1, 1))
bpy.ops.object.duplicate()
bpy.ops.transform.translate(value=(0, 0, 0), orient_type='LOCAL', orient_matrix=((0.836743, 0.547595, 0), (-0.138296, 0.21132, -0.967584), (-0.529844, 0.809619, 0.252551)), orient_matrix_type='LOCAL', constraint_axis=(True, True, True), mirror=False, use_proportional_edit=False, proportional_edit_falloff='SMOOTH', proportional_size=1, use_proportional_connected=False, use_proportional_projected=False)
bpy.ops.object.duplicate()
bpy.ops.transform.translate(value=(0, -3, 5.96046e-08), orient_type='LOCAL', orient_matrix=((0.836743, 0.547595, 0), (-0.138296, 0.21132, -0.967584), (-0.529844, 0.809619, 0.252551)), orient_matrix_type='LOCAL', constraint_axis=(True, True, True), mirror=False, use_proportional_edit=False, proportional_edit_falloff='SMOOTH', proportional_size=1, use_proportional_connected=False, use_proportional_projected=False)
bpy.ops.object.posemode_toggle()
bpy.context.scene.FFFGenPropertyGroup.auto_update_toggle = True
bpy.ops.object.duplicate()
Python: Traceback (most recent call last):
  File "C:\Users\AMiT\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\FFFGen\update.py", line 48, in modal
    modal_invoke()
  File "C:\Users\AMiT\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\FFFGen\update.py", line 93, in modal_invoke
    update_duplis()
  File "C:\Users\AMiT\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\FFFGen\update.py", line 135, in update_duplis
    bpy.ops.object.modifier_apply(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized
```

Wonder, if I missed something.

Seek your guidance.

Best Regards,
Amit.

**Comment by lsimic** [comment]
The "Possible incorrect orientation or possible incorrect scale" warning happens if the scale of the imported objects can be detected as incorrect (as some file formats for 3D data do not store any real world scale information"). 
The warning is there just as a warning to check, and possibly adjust the scale and orientation of the objects in order to match the expected values.

The error you are getting is as you are trying to run the addon with a newer version of blender (3.2), while the addon was written for an older version and is not compatible.
Could you please try with the older, LTS (long term support) version available here https://www.blender.org/download/lts/2-83/  and tell whether the issue persists or not. 

As blender 2.83 LTS support is (was) due to end in June 2022 I should probably update the addon to work with one of the newer LTS versions of Blender (probably 2.93. LTS expected to receive fixes until June 2023).

**Comment by amitjc** [comment]
Thank you for your prompt response.

Encountering same issue on Blender 2.83 LTS downloaded at the link above. 

Seek further guidance. 

Best,
Amit.

![Mandible_fibula_guides](https://user-images.githubusercontent.com/49818263/176889585-ce2a5c38-c8eb-46c8-bd1a-d880d7f57a31.png)
![Mandible_fibula_guides_2](https://user-images.githubusercontent.com/49818263/176889758-19c084a7-a627-428e-9d7c-2c90e7782bf5.png)
.

**Comment by lsimic** [comment]
The  "Possible incorrect orientation or possible incorrect scale" occurs if the rotation and/or size of the imported objects appears incorrect. It seems to be the case here. 
From the first screenshot, it is visible that the fibula is not aligned with the Y(green) axis, and from the second screenshot, it is visible that the size of the object appears too large. 

You can check the size by selecting the objects and opening the "item/transform" tab on the right. There you should adjust the scale and the position of both fibula and mandible, until the are of appropriate dimensions. Usually, the scale should be divisible by 10 (eg 10x, 0.1x etc...) or, different in the case of imperial to metric conversion (which will depend on the software and settings used to generate the file). But you can use the Item/transform to check and verify the exact dimensions. 

To adjust the scale, position and rotation, you can edit the fields in the item/transform tab, or use the appropriate rotate/transform/scale tools. Please note that both fibula and mandible should be scaled by an equal factor on all of the three axis.  

Once the objects have been positioned and resized correctly (fibula aligned with the Y axis, bottom of the mandible aligned with the x-y plane, with the front of the mandible facing in the positive direction of y axis) You can use Object - apply - all (object menu at the bottom left of the viewport) transforms with both fibula and mandible selected. 

You can also check out my colleague's channel for more videos. [https://www.youtube.com/channel/UCZycxONSzhQaTLy8lndgV_Q](https://www.youtube.com/channel/UCZycxONSzhQaTLy8lndgV_Q)

**Comment by amitjc** [comment]
Dear Sir,

Appreciate the much needed inputs and Vjekoslav Kopačin's video documentation.

Things are moving as expected.

Any possibility of update for latest blender release?

Thank you.

Best Regards,
Amit.
